-- Walking-skeleton schema: company (MDM-001) + append-only audit (AUDIT-SPRINT).
-- Migrations are forward-only and backward-compatible (practices.md).

-- Dedicated company-code sequence (MDM-001).
CREATE SEQUENCE IF NOT EXISTS company_code_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE company (
    company_code             VARCHAR(20)  PRIMARY KEY,
    name                     VARCHAR(200) NOT NULL,
    address                  VARCHAR(300) NOT NULL,
    tin                      VARCHAR(40),
    sec_registration_code    VARCHAR(60),
    incorporation_date       DATE,
    annual_meeting_date      DATE,
    president_name           VARCHAR(200),
    corporate_secretary_name VARCHAR(200)
);

CREATE TABLE audit_entry (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor       VARCHAR(100) NOT NULL,
    action      VARCHAR(100) NOT NULL,
    entity_ref  VARCHAR(200) NOT NULL,
    before_json TEXT,
    after_json  TEXT,
    occurred_at TIMESTAMP    NOT NULL
);

CREATE INDEX idx_audit_entity_ref ON audit_entry (entity_ref);
CREATE INDEX idx_audit_occurred_at ON audit_entry (occurred_at);
